### ISSUE TITLE
Cannot install ifnb dataset - 3.1.0 404 error. Not present.

### ISSUE THREAD

**Issue by kmshort** [satijalab/seurat-data#16]
I'm using SeuratData 0.2.1, R 3.6.2

`> InstallData("ifnb")
trying URL 'http://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.1.0.tar.gz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.1.0.tar.gz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'http://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.1.0.tar.gz': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘ifnb.SeuratData’ failed
Error in loadNamespace(name) : 
  there is no package called ‘ifnb.SeuratData’`

http://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.1.0.tar.gz isn't there.
However, 3.0.0 still is:
https://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.0.0.tar.gz

(I tried switching HTTP to HTTPS for 3.1, but there was no change).
Can someone please check that the file is there and named correctly?

For now I've just installed ifnb 3.0.0 using install.packages, rather than InstallData("ifnb") which automatically tries to grab the non-existant ifnb 3.1 version.

**Comment by andrewwbutler** [comment]
Hi,

Sorry for the late reply. Are you still experiencing this error? I've checked and the 3.1.0 version should be available at that location.
