### ISSUE TITLE
Issue with installation of data from SeuratData

### ISSUE THREAD

**Issue by JamesTayCam** [satijalab/seurat-data#18]
Hi, I am having issues dowloading the 'ifnb' data set from the SeuratData repository. Here is my console output:

> library(SeuratData)
> InstallData('ifnb')
Using cached data manifest, last updated at 2020-01-30 13:22:32
Error: No access to remote SeuratData repository, unable to install new datasets

**Comment by vHelmholtz** [comment]
Hello Satijalab,

Like JamesTayCam, I have also trouble to install the 'ifnb' data from the SeuratData, which is necessary for trying the vignette "Stimulated vs Control PBMCs". Could you please check this issue?

> InstallData("ifnb")
Installing package into ‘C:/Users/jongshin.kim/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'http://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.1.0.tar.gz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.1.0.tar.gz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'http://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.1.0.tar.gz': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘ifnb.SeuratData’ failed
Error in loadNamespace(name) : 
  there is no package called ‘ifnb.SeuratData’
>

**Comment by vHelmholtz** [comment]
I have solved this problem according to #15. Thanks!

**Comment by andrewwbutler** [comment]
I'm assuming this is resolved now but if not please reopen.
