### ISSUE TITLE
ifnb.list

### ISSUE THREAD

**Issue by jajcobyang** [satijalab/seurat-data#20]
Dear Sir or Madam,

I am using Seurat 3.1, ifnb.SeuratData 3.0 and following vignettes - Tutorial: Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses.

when I run 
`ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})`
error occured as follows:
` Error: Unexpected result (of class ‘NULL’ != ‘FutureResult’) retrieved for MultisessionFuture future (label = ‘future_lapply-3’, expression = ‘{; do.call(function(...) {; ...future.globals.maxSize.org <- getOption("future.globals.maxSize"); if (!identical(...future.globals.maxSize.org, ...future.globals.maxSize)) {; oopts <- options(future.globals.maxSize = ...future.globals.maxSize); on.exit(options(oopts), add = TRUE); ...; }; }, args = future.call.arguments); }’): . This suggests that the communication with MultisessionFuture worker (‘SOCKnode’ #3) is out of sync.`

So could you please tell me should I solve this problem?

Thanks a million for your attention.

Best,
Fan

**Comment by andrewwbutler** [comment]
Hi Fan,

Sorry for the delayed response. Try restarting your R session and try running without enabling `future`. If that doesn't resolve the issue, please post over on the main seurat issue [page](https://github.com/satijalab/seurat/issues).
