### ISSUE TITLE
Can't install data. Error: No access to remote SeuratData repository, unable to install new datasets

### ISSUE THREAD

**Issue by lc822** [satijalab/seurat-data#23]
Hi,

I have successfully installed SeuratData using `devtools::install_github('satijalab/seurat-data')` (version 0.2.1) and I am able to see available datasets using the `AvailableData()` command.

However, when I try to install the PBMC 3K dataset using `InstallData("pbmc3k")`, I get the following error:

> Using cached data manifest, last updated at 2020-04-07 10:27:02
> Error: No access to remote SeuratData repository, unable to install new datasets

What may be the reason for this?  I have looked at the similar issues but have not been able to find a solution.  I am using Seurat version 3.1.3 and R version 3.6.2.

Many thanks,
Lucy

**Comment by lvjackson** [comment]
Hi I am having this same problem and I wonder if you found a solution? 
Thanks so much!

Leandra

**Comment by lc822** [comment]
Hi @lvjackson,

I am not sure exactly what the problem was.  I have switched to R 4.0.0 now with Seurat 3.1.5 and SeuratData 0.2.1 and it seems to be working fine.

Best,
Lucy

**Comment by bethrusnak** [comment]
I also have this issue. Using R-4.0.3, Seurat 3.2.2, SeuratData  0.2.1

**Comment by AC-H** [comment]
Lucy, How have you switch the R and Seurat version? (I am using packrat)

**Comment by andrewwbutler** [comment]
It's possible you could see this if your internet connection is unstable/down. Hopefully this is resolved but feel free to reopen/comment if not.

**Comment by leezx** [comment]
I think it's better for Seurat to provide explicit download link for each dataset. However, they wrapped the download link/process with complicated R code. After look into the code, I found each dataset is a individual R package. Here is the direct R code to download it. `install.packages("thp1.eccite.SeuratData", repos="http://seurat.nygenome.org/", type = "source")`. You can change the datasets to whatever you want that presented in the `AvailableData()`.

**Comment by arnavaz** [comment]
Hi, 
is it possible to to run the function RunAzimuth() without internet connection?
thanks,
Arnavaz
