### ISSUE TITLE
error with installing spatial ver of Seurat

### ISSUE THREAD

**Issue by wfma** [satijalab/seurat-data#24]
Hello! I just tried to install the Seurat version for spatial transcriptiomic analysis using the following code:

`devtools::install_github("satijalab/seurat", ref = "spatial")`

I then encounter this error:

`Installing 8 packages: miniUI, spatstat, spatstat.utils, spatstat.data, deldir, abind, tensor, goftest
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) unable to access index for repository https://mojaveazure.github.io/loomR/bin/macosx/contrib/4.0:
  cannot open URL 'https://mojaveazure.github.io/loomR/bin/macosx/contrib/4.0/PACKAGES'`

I cannot visit the referenced website on my web browser, any suggestions?

Thank you, Wei

**Comment by andrewwbutler** [comment]
Hi Wei,

Sorry for the delayed response. The latest version of Seurat on CRAN (v3.2.1) contains all the code previously contained in the spatial branch. Installing as normal with `install.packages("Seurat")` should enable the spatial transcriptomic analyses you want to run.
