### ISSUE TITLE
Issue with installation of data from SeuratData.unable to install "pbmc3k.final" datasets

### ISSUE THREAD

**Issue by Aby-GGG** [satijalab/seurat-data#27]
Hi,

I have successfully installed SeuratData and I am able to see available datasets using the AvailableData() command.
![image](https://user-images.githubusercontent.com/58497378/96336696-2ff9f480-10b4-11eb-9caa-5af3debfd489.png)
However, when I try to install the "pbmc3k.final" dataset using InstallData("pbmc3k.final"), I get the following error:
![image](https://user-images.githubusercontent.com/58497378/96336564-5cf9d780-10b3-11eb-8d86-40d232ca7739.png)

What may be the reason for this?I am using Seurat version 3.1.3 and R version 3.6.3.

**Comment by bassanio** [comment]
Have you tried this way?
```
pbmc3k <- LoadData(ds = "pbmc3k.final")
```

**Comment by vgilbart** [comment]
In case some stubbles on this issue here's how to load `pbmc3k.final`:

```r
InstallData("pbmc3k")
pbmc3k <- LoadData("pbmc3k", type = "pbmc3k.final")

```
