### ISSUE TITLE
download timeout 

### ISSUE THREAD

**Issue by bernarddbj** [satijalab/seurat-data#29]
> InstallData("stxBrain")
trying URL 'http://seurat.nygenome.org/src/contrib/stxBrain.SeuratData_0.1.1.tar.gz'
Content type 'application/octet-stream' length 110346050 bytes (105.2 MB)
========
downloaded 18.7 MB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'http://seurat.nygenome.org/src/contrib/stxBrain.SeuratData_0.1.1.tar.gz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 19611317 != reported length 110346050
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://seurat.nygenome.org/src/contrib/stxBrain.SeuratData_0.1.1.tar.gz': Timeout of 60 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘stxBrain.SeuratData’ failed
Error in loadNamespace(name) : 
  there is no package called ‘stxBrain.SeuratData’

**Comment by Fan-iX** [comment]
you can set the timeout limit for download.packages() to 600s by `options(timeout=600)` , which may be enough for your downloading

**Comment by AMechels** [comment]
Encountered the same error today, @Fan-iX your solution worked, thank you very much!

**Comment by abhilashdasari** [comment]
I too encountered the same error today, @Fan-iX, your solution worked, thank you very much!
