### ISSUE TITLE
Full name of the L2 level annotations for the "bmcite" dataset

### ISSUE THREAD

**Issue by luoping1004** [satijalab/seurat-data#31]
Dear Seurat team members,

Thank you for generating these valuable datasets! 

Recently, I tried to use the bone marrow dataset ("bmcite") as reference to annotate single-cell data in my study. I noticed that l2 level annotations were available in the metadata slot. Although most of the these annotations were easy to understand, types such as 'CD8 Effector_1', 'CD8 Effector_2', 'CD8 Memory_1', 'CD8 Memory_2' were difficult to understand. I guess there are some markers that discriminate them?

Then I tried to find the answers in the paper that published this dataset. Unfortunately, I couldn't find any details about these cell types. Could anyone tell me the full name of these L2 annotations?

Thanks,

**Comment by andrewwbutler** [comment]
Hi,

You can find heatmaps of genes that define these annotations in Supplementary Figure 2G ([link](https://www.biorxiv.org/content/10.1101/2020.10.12.335331v1.supplementary-material)). Hopefully that makes the distinctions a bit more clear.
