### ISSUE TITLE
coercing “NULL” to “dgCMatrix - Error

### ISSUE THREAD

**Issue by khubebsiddiqui** [satijalab/seurat-data#34]
hi I am running this code and getting error:

> ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {x <- NormalizeData(x) x <- FindVariableFeatures(x, selection.method= "vst", nfeatures = 2000)}) 

The error is; unexpected symbol in "ifnb.list <-  lapply(X = ifnb.list, FUN = function(x) {x <- NormalizeData(x) x"

**Comment by khubebsiddiqui** [comment]
> ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
+     x <- NormalizeData(x)
+     x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
+ })

**Error in as(object = data, Class = "dgCMatrix") : 
  no method or default for coercing “NULL” to “dgCMatrix”
Called from: as(object = data, Class = "dgCMatrix")**

**Comment by andrewwbutler** [comment]
Hi,

This does not appear to be an issue related to the `SeuratData` package. It looks to be a code formatting issue but if the error persists, please post over on the main Seurat repo.
