### ISSUE TITLE
Seurat vignette mapping and annotating datasets

### ISSUE THREAD

**Issue by ncedi12** [satijalab/seurat-data#36]
Please assist
I'm busy trying to go through the Seurat vignette on annotating datasets using references. It uses the "panc8" pancreatic islets dataset which they say is contained within the SeuratData package. However I cannot install this data and keep getting the same error

#this is the vignette
library(Seurat)
library(SeuratData)
InstallData("panc8")
To construct a reference, we will identify ‘anchors’ between the individual datasets. First, we split the combined object into a list, with each dataset as an element (this is only necessary because the data was bundled together for easy distribution).

data("panc8")
pancreas.list <- SplitObject(panc8, split.by = "tech")
pancreas.list <- pancreas.list[c("celseq", "celseq2", "fluidigmc1", "smartseq2")]
 
#this is the error

> data("panc8")
Warning message:
In data("panc8") : data set 'panc8' not found
> pancreas.list <- SplitObject(panc8, split.by = "tech")
Error in is(x, "classRepresentation") : object 'panc8' not found
> InstallData("panc8")
trying URL 'http://seurat.nygenome.org/src/contrib/panc8.SeuratData_3.0.2.tar.gz'
Content type 'application/octet-stream' length 123194611 bytes (117.5 MB)
============================================
downloaded 104.0 MB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'http://seurat.nygenome.org/src/contrib/panc8.SeuratData_3.0.2.tar.gz' failed
In addition: There were 38 warnings (use warnings() to see them)
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package 'panc8.SeuratData' failed
Error in loadNamespace(name) : 
  there is no package called 'panc8.SeuratData'

How can I get this data to keep with the vignette

**Comment by andrewwbutler** [comment]
Hi,

It looks like your download timed out. You can adjust this with `options(timeout=X)` to give the download longer to complete.

**Comment by ncedi12** [comment]
This worked beautifully, thank you very much.
I'm new to programming and am fascinated by the community that is available to help troubleshoot issue. 
Keep going, much appreciated
