### ISSUE TITLE
SeuratData won't install datasets

### ISSUE THREAD

**Issue by jmosullivan** [satijalab/seurat-data#38]
Hi, 

I am having a similar issue to what others are reporting. 

I am trying to install "bmcite" dataset with no luck with any of the below: 

InstallData("bmcite.SeuratData")
InstallData("bmcite")
install.packages("https://seurat.nygenome.org/src/contrib/bmcite.SeuratData_0.3.0.tar.gz", repos = NULL, type = "source")

When I installed SeuratData it gave the following warning:

Warning in if (is.na(desc)) { :
  the condition has length > 1 and only the first element will be used

Any help with resolving would be much appreciated. 

Thanks

Jennifer

**Comment by andrewwbutler** [comment]
Hi Jennifer,

This is just a warning and shouldn't affect the installation of datasets. However, if you want to silence the warning, you can try installing the `develop` branch.

```R
remotes::install_github("satijalab/seurat-data", ref = "develop")
```
