### ISSUE TITLE
VlnPlot shows several perfectly lines of cells. 

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat-data#39]
Hello,

As you can see on below VlnPlot, you will notice that cells seem to be aligning perfectly along the same gene expression value across all cell types.

Is this abnormal? What's the likely reason and do you have any recommendations???

VlnPlot(immune.combined.sct, features = "NAMPT", pt.size = 0.2, ncol = 1) + NoLegend()

![image](https://user-images.githubusercontent.com/68268222/130353772-baccfea9-729d-4cd8-96bd-9748360369fb.png)

**Comment by andrewwbutler** [comment]
This is a question probably more appropriate for the main `seurat` github repo so if you have further questions I would recommend posting there. My guess, given that I don't know what data this is or how you processed it, is that you haven't normalized it and the "lines" of expression correspond to UMI counts of expression for this gene.
