### ISSUE TITLE
LoadData fails for Brain

### ISSUE THREAD

**Issue by MarcElosua** [satijalab/seurat-data#43]
Hello,

Thanks for putting together this resource. It makes it very easy to source Seurat data! In the past I haven't had any issues using it but I am now currently facing some issues when using it.

I'm running the following commands to install, download, and load data the stxBrain data:
```
install_github('satijalab/seurat-data')
SeuratData::InstallData(ds = "stxBrain.SeuratData")
x <- SeuratData::LoadData(ds = "stxBrain.SeuratData")
```
The package installation and data download work perfect but when running LoadData I get the following error:
`Error: Could not find dataset 'stxBrain', please check manifest and try again`

Any help would be really appreciate it! Thanks so much!

I am running this on this machine:
```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie                 
```

**Comment by andrewwbutler** [comment]
Hi,

This dataset consists of 4 brain slices that are stored separately (see `?stxBrain`). So to load one in for example,

```R
LoadData("stxBrain", type = "anterior1")
```
