### ISSUE TITLE
PBMC3K Data Install Problems

### ISSUE THREAD

**Issue by bigtimecodersean** [satijalab/seurat-data#46]
Hey! 

I am trying to download to download the 'pbmc3k' data on the Reference Mapping tutorial. 

When I use either: InstallData('pbmc3k.SeuratData') or InstallData('pbmc3k'), I get the following message: 

trying URL 'http://seurat.nygenome.org/src/contrib/pbmc3k.SeuratData_3.1.4.tar.gz'
Content type 'application/octet-stream' length 93780025 bytes (89.4 MB)

downloaded 1.2 MB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'http://seurat.nygenome.org/src/contrib/pbmc3k.SeuratData_3.1.4.tar.gz' failed
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘pbmc3k.SeuratData’ failed
Error in loadNamespace(name) : 
  there is no package called ‘pbmc3k.SeuratData’

-----------------------------------------------------------------------------

Any ideas for what to try? 

Thanks!

**Comment by bigtimecodersean** [comment]
Turns out the exact same message pops up when I try to install other SeuratData, such as "bmcite".For reference, I am running: Seurat_4.0.6 and SeuratData_0.2.1

**Comment by GeertvanGeest** [comment]
Setting `timeout` at `options` indeed fixed it for me (setting it to 240 secs here):
```R
library(SeuratData)
options(timeout = 240)
InstallData("pbmc3k")
```
Default is 60 seconds.
