### ISSUE TITLE
Tutorial: "NULL" to "dgMatrix"

### ISSUE THREAD

**Issue by CD-man** [satijalab/seurat-data#47]
I have run into an issue with the [tutorial](https://satijalab.org/seurat/articles/integration_introduction.html) where I get the following error. I am running Win11 and a fresh install of R and RStudio. 

Any help you could offer would be greatly appreciated. 

`Error in as(object = data, Class = "dgCMatrix") : no method or default for coercing “NULL” to “dgCMatrix”`

I then clicked "Show Traceback": 

```
Error in as(object = data, Class = "dgCMatrix") : no method or default for coercing “NULL” to “dgCMatrix”
7. stop(gettextf("no method or default for coercing %s to %s", dQuote(thisClass), 
dQuote(Class)), domain = NA)
6. as(object = data, Class = "dgCMatrix")
5. LogNormalize(data = object, scale.factor = scale.factor, verbose = verbose)
4. NormalizeData.default(x)
3. NormalizeData(x)
2. FUN(X[[i]], ...)
1. lapply(X = ifnb.list, FUN = function(x) {
x <- NormalizeData(x)
x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
```

**Comment by andrewwbutler** [comment]
Hi,

It looks like you are trying to apply these functions to something that is `NULL`. Check that your list (`infb.list`) contains `Seurat` objects as each element and is not `NULL`.
