### ISSUE TITLE
Issue with SeuratData

### ISSUE THREAD

**Issue by garsat** [satijalab/seurat-data#5]
Hi,
I successed to install SeuratWrappers and I tried to install SeuratData but it doesn't work. Does any one has an idea about this problem.
Thanks

devtools::install_github('satijalab/seurat-data')
Downloading GitHub repo satijalab/seurat-data@master
   checking for file ‘/private/var/folders/qz/73f1ych53d96d4m0rj5xrlt00000gp/T/RtmpVCP2Vk/remotes8765cfd62c4/sat✔  checking for file ‘/private/var/folders/qz/73f1ych53d96d4m0rj5xrlt00000gp/T/RtmpVCP2Vk/remotes8765cfd62c4/satijalab-seurat-data-56a538f/DESCRIPTION’ (374ms)
─  preparing ‘SeuratData’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘SeuratData_0.1.0.tar.gz’
   
* installing *source* package ‘SeuratData’ ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning: unable to access index for repository https://seurat.nygenome.org/src/contrib:
  impossible d'ouvrir l'URL 'https://seurat.nygenome.org/src/contrib/PACKAGES'
Error: package or namespace load failed for ‘SeuratData’:
 .onAttach failed in attachNamespace() for 'SeuratData', details:
  call: pkg[["Package"]]
  error: indice hors limites
Erreur : le chargement a échoué
Exécution arrêtée
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/SeuratData’
Erreur : Failed to install 'SeuratData' from GitHub:
  (converti depuis l'avis) installation of package ‘/var/folders/qz/73f1ych53d96d4m0rj5xrlt00000gp/T//RtmpVCP2Vk/file8767183e20c/SeuratData_0.1.0.tar.gz’ had non-zero exit status

**Comment by mojaveazure** [comment]
Hi @garsat,

Can you post the output of the following from the command line (not R)?

```bash
ping -c 5 -W 1 https://seurat.nygenome.org
```

**Comment by garsat** [comment]
Hello

this is the output 

ping -c 5 -W 1 https://seurat.nygenome.org
Erreur : unexpected numeric constant in "ping -c 5"

**Comment by mojaveazure** [comment]
Are you running this from the command line/terminal/bash or from R?

**Comment by garsat** [comment]
I'm sorry 
this is the output from the terminal 


iMac-de-Imac:~ invite$ ping -c 5 -W 1 https://seurat.nygenome.org
ping: cannot resolve https://seurat.nygenome.org: Unknown host

**Comment by mojaveazure** [comment]
Okay, can you try again but without the `https://`?

```bash
ping -c 5 -W 1 seurat.nygenome.org
```

**Comment by garsat** [comment]
iMac-de-Imac:~ invite$ ping -c 5 -W 1 seurat.nygenome.org
PING seurat.nygenome.org (162.220.30.75): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3

--- seurat.nygenome.org ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss
iMac-de-Imac:~ invite$

**Comment by mojaveazure** [comment]
Weird, I'm not sure what's going on with that. Last test, are you able to visit https://seurat.nygenome.org in a web browser?

**Comment by garsat** [comment]
Yes

SeuratData
SeuratData is a mechanism for distributing datasets in the form of Seurat objects using R’s internal package and data management systems. It represents an easy way for users to get access to datasets that are used in the Seurat vignettes.

Installation
Installation of SeuratData can be accomplished through devtools

devtools::install_github('satijalab/seurat-data')

**Comment by mojaveazure** [comment]
Interesting. Before running the install function, can you set the `download.file.method` option to `"wget"` ([and ensure you have wget installed before running this](https://stackoverflow.com/questions/33886917/how-to-install-wget-in-macos))?

```R
# In R
option(download.file.method = 'wget')
devtools::install_github('satijalab/seurat-data')
```

**Comment by garsat** [comment]
It still the same error after the installation of wget

wget its installed ;
iMac-de-Imac:~ invite$ brew install wget
Warning: wget 1.20.3_1 is already installed and up-to-date

the error ;

options(download.file.method = 'wget')
> devtools::install_github('satijalab/seurat-data')
Downloading GitHub repo satijalab/seurat-data@master
   checking for file ‘/private/var/folders/qz/73f1ych53d96d4m0rj5xrlt00000gp/T/R✔  checking for file ‘/private/var/folders/qz/73f1ych53d96d4m0rj5xrlt00000gp/T/RtmpQ5ypVB/remotes20857343e238/satijalab-seurat-data-56a538f/DESCRIPTION’
─  preparing ‘SeuratData’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘SeuratData_0.1.0.tar.gz’
   
* installing *source* package ‘SeuratData’ ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning: unable to access index for repository https://seurat.nygenome.org/src/contrib:
  impossible d'ouvrir l'URL 'https://seurat.nygenome.org/src/contrib/PACKAGES'
Error: package or namespace load failed for ‘SeuratData’:
 .onAttach failed in attachNamespace() for 'SeuratData', details:
  call: pkg[["Package"]]
  error: indice hors limites
Erreur : le chargement a échoué
Exécution arrêtée
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/SeuratData’
Erreur : Failed to install 'SeuratData' from GitHub:
  (converti depuis l'avis) installation of package ‘/var/folders/qz/73f1ych53d96d4m0rj5xrlt00000gp/T//RtmpQ5ypVB/file20855da8b1d6/SeuratData_0.1.0.tar.gz’ had non-zero exit status
>

**Comment by garsat** [comment]
I checked 
I can't access to this link :
https://seurat.nygenome.org/src/contrib
but I can for this 
https://seurat.nygenome.org/

**Comment by mojaveazure** [comment]
Are you getting a 403 error for https://seurat.nygenome.org/src/contrib? If so, that's normal.

What about https://seurat.nygenome.org/src/contrib/PACKAGES; does this attempt to start downloading a file?

**Comment by garsat** [comment]
Yes I got  403 error
Yes when I open the link , it download the file PACKAGES

**Comment by mojaveazure** [comment]
Okay, so you're able to reach our repository except on the command line. I would assume that running

```bash
wget https://seurat.nygenome.org/src/contrib/PACKAGES
```

on the command line would fail. If it does, then I would talk with your IT department about this. If it doesn't, then it would appear that something is wrong with your R installation, and there's very little we can do to debug. One thing I can suggest is by playing around with configuring [`download.file`](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/download.file.html), mainly the method for it. This should be configurable using `options(download.file.method)`

If all else fails, you can try setting `options(SeuratData.repo.use = "https://seurat-data-ran.s3.us-east-2.amazonaws.com/")` before installing. Please note, this repository is not permanent, and I strongly urge checking with your IT department about your iMac's inability to access our repository.

**Comment by ltosti** [comment]
Hi @mojaveazure ,

I'm having right now a similar error when I try ```library(SeuratData)```
```
Error: package or namespace load failed for ‘SeuratData’:
 .onAttach failed in attachNamespace() for 'SeuratData', details:
  call: x[[2]]
  error: subscript out of bounds
Traceback:

1. library(SeuratData)
2. tryCatch({
 .     attr(package, "LibPath") <- which.lib.loc
 .     ns <- loadNamespace(package, lib.loc)
 .     env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)
 . }, error = function(e) {
 .     P <- if (!is.null(cc <- conditionCall(e))) 
 .         paste(" in", deparse(cc)[1L])
 .     else ""
 .     msg <- gettextf("package or namespace load failed for %s%s:\n %s", 
 .         sQuote(package), P, conditionMessage(e))
 .     if (logical.return) 
 .         message(paste("Error:", msg), domain = NA)
 .     else stop(msg, call. = FALSE, domain = NA)
 . })
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. value[[3L]](cond)
6. stop(msg, call. = FALSE, domain = NA)
```

But it was working fine until yesterday; any suggestion?
