### ISSUE TITLE
InstallData("pbmc3k") error

### ISSUE THREAD

**Issue by partrita** [satijalab/seurat-data#70]
```bash
Using cached data manifest, last updated at 2023-06-16 14:55:40

Error: No access to remote SeuratData repository, unable to install new datasets
Traceback:

1. InstallData("pbmc3k")
2. stop("No access to remote SeuratData repository, unable to install new datasets", 
 .     call. = FALSE)
```

I guess, This repo not maintained properly.

**Comment by andreagrioni** [comment]
I have the same issue, I tried the solution [here](https://github.com/satijalab/seurat-data/issues/23#issuecomment-1227111059) but it did not sove it.

**Comment by crystalizee** [comment]
exact same error

**Comment by KSDalton** [comment]
exact same error

**Comment by bbimber** [comment]
We're also hitting this issue. Did anyone find a solution?

**Comment by afrias90** [comment]
I had this issue for the 'ifnb' dataset (but i can grab the pbmc3k dataset too now), I was able to solve this with downloading devtools (may require restarting R) 
# Install devtools from CRAN
install.packages("devtools")

# Or the development version from GitHub:
# install.packages("devtools")
devtools::install_github("r-lib/devtools")

and also using the link provided in another answer:
install.packages("https://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.0.0.tar.gz", repos = NULL, type = "source")

Don't forget load the library
library(SeuratData)
InstallData("pbmc3k")

Otherwise, I originally got the raw data from here, unzipped with with untar() and manually put the file 'filtered_gene_bc_matrices' in my workspace to overcome that first step.
https://cf.10xgenomics.com/samples/cell/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz

**Comment by ahdee** [comment]
This issue seem to come up a lot; here is my solution for **panc8** but is the same regardless of what dataset you are trying to download. 

```
# note the version of seurat, else use UpdateSeuratObject
AvailableData()

## I suspect that failing is due to network error timing out. 
# failed -- however copy the url 
InstallData("panc8")

# failed 
install.packages("https://seurat.nygenome.org/src/contrib/panc8.SeuratData_3.0.2.tar.gz", repos = NULL, type = "source")

## go to bash and use <cd /tmp; wget https://seurat.nygenome.org/src/contrib/panc8.SeuratData_3.0.2.tar.gz>
install.packages("/tmp/panc8.SeuratData_3.0.2.tar.gz", repos = NULL, type = "source")

# then load it, do not just load panc8 
library (panc8.SeuratData )
data("panc8")
# my is ver 4  so  I need to update the data 
panc8<-UpdateSeuratObject(panc8)
## works as expected now! 

pancreas.list <- SplitObject(panc8, split.by = "tech")
pancreas.list <- pancreas.list[c("celseq", "celseq2", "fluidigmc1", "smartseq2")]
```

**Comment by IrinaVKuznetsova** [comment]
same here
pbmc3k <- [LoadData](https://rdrr.io/pkg/SeuratData/man/LoadData.html)("pbmc3k")
`"Error: Cannot find dataset pbmc3k"`

**Comment by partrita** [comment]
> same here pbmc3k <- [LoadData](https://rdrr.io/pkg/SeuratData/man/LoadData.html)("pbmc3k") `"Error: Cannot find dataset pbmc3k"`

for pbmc3k data set, just download [this](https://cf.10xgenomics.com/samples/cell/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz)

Try this.
```R
library(Seurat)
pbmc.data <- Read10X(data.dir = "../data/pbmc3k/filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc
```

**Comment by AzureLii** [comment]
same erro, Seems to be a network problem, you can try to download several times, and try to keep on the Rstudio download bar page.....

![Snipaste_2024-06-19_10-19-30](https://github.com/satijalab/seurat-data/assets/125962486/8c0711d8-a286-43d8-9c23-99964a14f86a)

**Comment by partrita** [comment]
> same erro, Seems to be a network problem, you can try to download several times, and try to keep on the Rstudio download bar page.....
> 
> ![Snipaste_2024-06-19_10-19-30](https://private-user-images.githubusercontent.com/125962486/340891304-8c0711d8-a286-43d8-9c23-99964a14f86a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODI5OTEsIm5iZiI6MTcxODc4MjY5MSwicGF0aCI6Ii8xMjU5NjI0ODYvMzQwODkxMzA0LThjMDcxMWQ4LWEyODYtNDNkOC05YzIzLTk5OTY0YTE0Zjg2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwNzM4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDI4ZjI4ZWRmOWU2OThjOWFiNGNiZjExNzMyNTRhMGRmNmRhOWFhNGM3MmQ4MDUzMTQ2YjI3NjAwZGFjNzc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wLeNOsOdpFRcAGC6NmKquE5YHCr9dzHWnBsy5n1gNIk)

You could manually download files and make object.

**Comment by AzureLii** [comment]
> > same erro, Seems to be a network problem, you can try to download several times, and try to keep on the Rstudio download bar page.....
> > ![Snipaste_2024-06-19_10-19-30](https://private-user-images.githubusercontent.com/125962486/340891304-8c0711d8-a286-43d8-9c23-99964a14f86a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODI5OTEsIm5iZiI6MTcxODc4MjY5MSwicGF0aCI6Ii8xMjU5NjI0ODYvMzQwODkxMzA0LThjMDcxMWQ4LWEyODYtNDNkOC05YzIzLTk5OTY0YTE0Zjg2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwNzM4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDI4ZjI4ZWRmOWU2OThjOWFiNGNiZjExNzMyNTRhMGRmNmRhOWFhNGM3MmQ4MDUzMTQ2YjI3NjAwZGFjNzc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wLeNOsOdpFRcAGC6NmKquE5YHCr9dzHWnBsy5n1gNIk)
> 
> You could manually download files and make a seurat object.

Thanks！This is also a good idea, tody, I found another method - installing packages locally. For details, please refer to: https://github.com/satijalab/seurat-data/issues/15
