### ISSUE TITLE
Can not install!

### ISSUE THREAD

**Issue by lessonskit** [satijalab/seurat-data#9]
There are always errors when we install this package. Error is as follows.

Warning: unable to access index for repository https://seurat.nygenome.org/src/contrib:
  无法打开URL'https://seurat.nygenome.org/src/contrib/PACKAGES'
Error: package or namespace load failed for 'SeuratData':
 .onAttach failed in attachNamespace() for 'SeuratData', details:
  call: pkg[["Package"]]
  error: 下标出界
错误: 载入失败
停止执行
ERROR: loading failed
* removing 'D:/R-3.5.1/library/SeuratData'
In R CMD INSTALL
Installation failed: Command failed (1)

What should we do?

**Comment by iiiir** [comment]
Do you have access to the website, or it was blocked?
https://seurat.nygenome.org/
Can you download this file?
https://seurat.nygenome.org/src/contrib/PACKAGES

**Comment by lessonskit** [comment]
Dear Shuoguo Wang,


Thank you very much for your reply. We've solved the problem now.


Thank you and best regards.
Yours sincerely,

Zhenyuan Yu

&nbsp;
------------------ Original ------------------

**Comment by Aby-GGG** [comment]
I have the same problem as you. How did you solve the problem then. Can you tell me? Thank you



无法打开URL'https://seurat.nygenome.org/src/contrib/PACKAGES'
Error: package or namespace load failed for 'SeuratData':
 .onAttach failed in attachNamespace() for 'SeuratData', details:
  call: pkg[["Package"]]
  error: 下标出界
错误: 载入失败
停止执行
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Aby/Documents/R/win-library/3.6/SeuratData'
Error: Failed to install 'satijalab-seurat-data-56a538f.tar.gz' from local:
  (converted from warning) installation of package ‘C:/Users/Aby/AppData/Local/Temp/RtmpI1raHF/file6becc0a3a4d/SeuratData_0.1.0.tar.gz’ had non-zero exit status
